FROM ubuntu:jammy-20221101

RUN apt-get update \
  && apt-get install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    curl \
    dnsutils \
    iputils-ping \
    iproute2
