name: ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - ubuntu/Dockerfile
      - .github/workflows/ubuntu.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: ffmpeg/Dockerfile

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/bratteng/toolkit/ubuntu
          tags: |
            type=raw,value=latest

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.8.0
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.12.0
        with:
          file: ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.actor != 'dependabot[bot]' || github.actor != 'renovate[bot]' }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
